backend:
  name: github
  repo: uinosuke/portforio
  branch: main
  auth_scope: repo
  app_id: Ov23litHaGjKqGnNqyxf

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "works"
    label: "作品"
    folder: "src/data/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "タグ", name: "tags", widget: "list" }
      - { label: "メモ", name: "memo", widget: "text" }
      - { label: "画像", name: "image", widget: "image" }